//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Shared._Layout", typeof(_Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string LayoutAccount {
            get {
                return ResourceManager.GetString("LayoutAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string LayoutAdmin {
            get {
                return ResourceManager.GetString("LayoutAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this.
        /// </summary>
        public static string LayoutAreYouSureYouWantToDeleteThis {
            get {
                return ResourceManager.GetString("LayoutAreYouSureYouWantToDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string LayoutCategory {
            get {
                return ResourceManager.GetString("LayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string LayoutComment {
            get {
                return ResourceManager.GetString("LayoutComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string LayoutConfirmPassword {
            get {
                return ResourceManager.GetString("LayoutConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        public static string LayoutDefect {
            get {
                return ResourceManager.GetString("LayoutDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LayoutEmail {
            get {
                return ResourceManager.GetString("LayoutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string LayoutFirstName {
            get {
                return ResourceManager.GetString("LayoutFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password.
        /// </summary>
        public static string LayoutForgotYourPassword {
            get {
                return ResourceManager.GetString("LayoutForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string LayoutHello {
            get {
                return ResourceManager.GetString("LayoutHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LayoutHome {
            get {
                return ResourceManager.GetString("LayoutHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string LayoutInventory {
            get {
                return ResourceManager.GetString("LayoutInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LayoutLastName {
            get {
                return ResourceManager.GetString("LayoutLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LayoutLogin {
            get {
                return ResourceManager.GetString("LayoutLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LayoutLogout {
            get {
                return ResourceManager.GetString("LayoutLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string LayoutManage {
            get {
                return ResourceManager.GetString("LayoutManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string LayoutManager {
            get {
                return ResourceManager.GetString("LayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        public static string LayoutManufacturer {
            get {
                return ResourceManager.GetString("LayoutManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string LayoutMoreInfo {
            get {
                return ResourceManager.GetString("LayoutMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string LayoutOrder {
            get {
                return ResourceManager.GetString("LayoutOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LayoutPassword {
            get {
                return ResourceManager.GetString("LayoutPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string LayoutPrivacy {
            get {
                return ResourceManager.GetString("LayoutPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string LayoutProduct {
            get {
                return ResourceManager.GetString("LayoutProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products in categories.
        /// </summary>
        public static string LayoutProductInCategory {
            get {
                return ResourceManager.GetString("LayoutProductInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered products.
        /// </summary>
        public static string LayoutProductInOrder {
            get {
                return ResourceManager.GetString("LayoutProductInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned products.
        /// </summary>
        public static string LayoutProductReturned {
            get {
                return ResourceManager.GetString("LayoutProductReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold products.
        /// </summary>
        public static string LayoutProductSold {
            get {
                return ResourceManager.GetString("LayoutProductSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products with defect.
        /// </summary>
        public static string LayoutProductWithDefect {
            get {
                return ResourceManager.GetString("LayoutProductWithDefect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LayoutRegister {
            get {
                return ResourceManager.GetString("LayoutRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string LayoutRegisterAsANewUser {
            get {
                return ResourceManager.GetString("LayoutRegisterAsANewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string LayoutRememberMe {
            get {
                return ResourceManager.GetString("LayoutRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string LayoutReturn {
            get {
                return ResourceManager.GetString("LayoutReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string LayoutSale {
            get {
                return ResourceManager.GetString("LayoutSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesPerson.
        /// </summary>
        public static string LayoutSalesPerson {
            get {
                return ResourceManager.GetString("LayoutSalesPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shippers.
        /// </summary>
        public static string LayoutShipper {
            get {
                return ResourceManager.GetString("LayoutShipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        public static string LayoutShop {
            get {
                return ResourceManager.GetString("LayoutShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LayoutSignIn {
            get {
                return ResourceManager.GetString("LayoutSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLES.
        /// </summary>
        public static string LayoutTABLES {
            get {
                return ResourceManager.GetString("LayoutTABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LayoutUsers {
            get {
                return ResourceManager.GetString("LayoutUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string LayoutWelcome {
            get {
                return ResourceManager.GetString("LayoutWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many2Many Tables.
        /// </summary>
        public static string Many2ManyTables {
            get {
                return ResourceManager.GetString("Many2ManyTables", resourceCulture);
            }
        }
    }
}
