//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Identity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountManage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Identity.AccountManage", typeof(AccountManage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another service to log in..
        /// </summary>
        public static string AddAnotherLoginService {
            get {
                return ResourceManager.GetString("AddAnotherLoginService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string Associate {
            get {
                return ResourceManager.GetString("Associate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication App.
        /// </summary>
        public static string AuthApp {
            get {
                return ResourceManager.GetString("AuthApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Uri.
        /// </summary>
        public static string AuthenticatorUri {
            get {
                return ResourceManager.GetString("AuthenticatorUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app.
        ///        If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string AuthKeyProcess {
            get {
                return ResourceManager.GetString("AuthKeyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string CheckEmailResetPassword {
            get {
                return ResourceManager.GetString("CheckEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string ConfigureAuthApp {
            get {
                return ResourceManager.GetString("ConfigureAuthApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string DeleteAndCloseAccount {
            get {
                return ResourceManager.GetString("DeleteAndCloseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete personal data.
        /// </summary>
        public static string DeletePersonalData {
            get {
                return ResourceManager.GetString("DeletePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string DeletingThisData {
            get {
                return ResourceManager.GetString("DeletingThisData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys..
        /// </summary>
        public static string Disable2FAText {
            get {
                return ResourceManager.GetString("Disable2FAText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string DisableTwoFactorAuthentication {
            get {
                return ResourceManager.GetString("DisableTwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string Download2faApp {
            get {
                return ResourceManager.GetString("Download2faApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Personal Data.
        /// </summary>
        public static string DownloadPersonalData {
            get {
                return ResourceManager.GetString("DownloadPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address for this site below and click the Register button to finish
        ///    logging in..
        /// </summary>
        public static string EmailToFinishLogIn {
            get {
                return ResourceManager.GetString("EmailToFinishLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string ErrorMessagePasswordLength {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ErrorMessagePasswordNoMatch {
            get {
                return ResourceManager.GetString("ErrorMessagePasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string FinishingQRCode {
            get {
                return ResourceManager.GetString("FinishingQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser..
        /// </summary>
        public static string ForgetThisBrowser {
            get {
                return ResourceManager.GetString("ForgetThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string Generate2FACodes {
            get {
                return ResourceManager.GetString("Generate2FACodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate recovery codes.
        /// </summary>
        public static string GenerateRecoveryCodes {
            get {
                return ResourceManager.GetString("GenerateRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
        ///        used in an authenticator app you should reset your authenticator keys.
        /// </summary>
        public static string GeneratingNewCodes {
            get {
                return ResourceManager.GetString("GeneratingNewCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place!.
        /// </summary>
        public static string HideYourCodes {
            get {
                return ResourceManager.GetString("HideYourCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string IfResetAuthKey {
            get {
                return ResourceManager.GetString("IfResetAuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;3 recovery codes left..
        /// </summary>
        public static string LessThanThreeRecoveryCodesLeft {
            get {
                return ResourceManager.GetString("LessThanThreeRecoveryCodesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string LoginProtectedWith2FA {
            get {
                return ResourceManager.GetString("LoginProtectedWith2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login using your {0} account.
        /// </summary>
        public static string LoginUsingService {
            get {
                return ResourceManager.GetString("LoginUsingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your have successfully logged out!.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string LoseDeviceWithCode {
            get {
                return ResourceManager.GetString("LoseDeviceWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageExternalLogins {
            get {
                return ResourceManager.GetString("ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must generate a new set of recovery codes before you can log in with a recovery code.
        /// </summary>
        public static string MustGenerateRecoveryCode {
            get {
                return ResourceManager.GetString("MustGenerateRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can log in with a recovery code.
        /// </summary>
        public static string NoAccessToAuthDevice {
            get {
                return ResourceManager.GetString("NoAccessToAuthDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string NoAccesToResource {
            get {
                return ResourceManager.GetString("NoAccesToResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        ///    account so you can log in without an external login..
        /// </summary>
        public static string NoLocalAccount {
            get {
                return ResourceManager.GetString("NoLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string NoRecoveryCode {
            get {
                return ResourceManager.GetString("NoRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your have 1 recovery code left..
        /// </summary>
        public static string OneRecoveryCodeLeft {
            get {
                return ResourceManager.GetString("OneRecoveryCodeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset..
        /// </summary>
        public static string PasswordHasBeenReset {
            get {
                return ResourceManager.GetString("PasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string PersonalDataInfo {
            get {
                return ResourceManager.GetString("PersonalDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        public static string RecoveryCodes {
            get {
                return ResourceManager.GetString("RecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this machine?.
        /// </summary>
        public static string RememberMachine {
            get {
                return ResourceManager.GetString("RememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this {0} login from your account.
        /// </summary>
        public static string RemoveThisLogin {
            get {
                return ResourceManager.GetString("RemoveThisLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide
        ///    an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string RequestLoginRecoveryCode {
            get {
                return ResourceManager.GetString("RequestLoginRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string ResetAuthKey {
            get {
                return ResourceManager.GetString("ResetAuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes..
        /// </summary>
        public static string ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("ResetRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string SendVerificationEmail {
            get {
                return ResourceManager.GetString("SendVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared key.
        /// </summary>
        public static string SharedKey {
            get {
                return ResourceManager.GetString("SharedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should generate a new set of recovery codes before you can log in with a recovery code.
        /// </summary>
        public static string ShouldGenerateRecoveryCode {
            get {
                return ResourceManager.GetString("ShouldGenerateRecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status message.
        /// </summary>
        public static string StatusMessage {
            get {
                return ResourceManager.GetString("StatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string SuccessfullyAuthenticated {
            get {
                return ResourceManager.GetString("SuccessfullyAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email.
        /// </summary>
        public static string ThankConfirmEmail {
            get {
                return ResourceManager.GetString("ThankConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string ThisActionOnlyDisabled2FA {
            get {
                return ResourceManager.GetString("ThisActionOnlyDisabled2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable QR code generation please read our documentation.
        /// </summary>
        public static string ToEnableQRCode {
            get {
                return ResourceManager.GetString("ToEnableQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps.
        /// </summary>
        public static string ToUseAuthApp {
            get {
                return ResourceManager.GetString("ToUseAuthApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication code.
        /// </summary>
        public static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifitseeri.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
    }
}
